### ISSUE TITLE
Verify support for TLS 1.1 and 1.2

### ISSUE THREAD

**Issue by dluc** [Azure/reverse-proxy-dotnet#21]
> The PCI Security Standards Council announced that PCI-compliant websites must transition from TLS version 1.0 to TLS 1.1 or higher by June 30, 2018.

> After June 30, 2018, all newly created App Service apps will be automatically configured to require TLS 1.2. You’ll still retain the option to configure earlier TLS versions for your apps, if necessary, for compatibility with older browser clients.

The tests should cover permutations of browsers, versions, platforms.

**Comment by ppathan** [comment]
@zhang-hua Can you take a look at this, we might be compliant?

**Comment by zhang-hua** [comment]
@ppathan , correct. we have enabled TLS 1.2.  this can be closed now.

**Comment by dluc** [comment]
@zhang-hua is it possible to write tests to verify TLS 1.2 support?
