### ISSUE TITLE
404 Error on visualisations when using a large number of devices.

### ISSUE THREAD

**Issue by jmo808** [Azure/reverse-proxy-dotnet#22]
# Type of issue 

- [x] Bug
- [ ] New feature
- [ ] Enhancement

# Description 
404-Not Found on the System Alarms, System KPI's, Telemetry tables with a large number of devices.
Inspected the streaming application logs and noticed this error:
The request filtering module is configured to deny a request where the query string is too long.
...

# Steps to reproduce 

1. Deploy the solution with a large quantity of devices (I used 100 devices)

# Expected behavior 

When accessing the Web UI the live charts should actually work.
...

# Current behavior 

Visualizations show 404 not found error.
...

# Known workarounds 

Alter the web.config of the web app with this addition:
```
<?xml version="1.0"?>
<configuration>
  <system.webServer>
    <security>
      <requestFiltering>
        <requestLimits maxQueryString="10000" />
      </requestFiltering>
    </security>
  </system.webServer>
</configuration>
```
...

# Possible solution 

...

# Context and Environment
* Operating System: Azure Web Site
* GitHub branch: master
* .NET Runtime: 4.5

# Code to reproduce the bug

**Comment by ppathan** [comment]
This bug belongs in webui. It is in our backlog
