### ISSUE TITLE
Make following redirects optional

### ISSUE THREAD

**Issue by KeesCBakker** [Azure/reverse-proxy-dotnet#28]
# Type of issue 

- [ ] Bug
- [x] New feature
- [x] Enhancement

# Description 
I like to be able to set whether the redirect of my end-point should be executed by the reverse proxy. It currently handles the redirect inside the proxy.

# Possible solution 
Let's add a AutoRedirect setting.

**Comment by dluc** [comment]
@KeesCBakker have you tested the redirection with POST/PUT/DELETE methods?  If I remember correctly, redirecting those requests requires some special consideration, including security.

In any case, I think a HTTP proxy should be as transparent as possible, leaving to clients and servers to figure out how they want to work together. A client might consider a 301/302 an error, or might want to know that the request was sent to a deprecated endpoint which is now redirecting, etc.

Happy to discuss this, however I'll close as "won't fix" for the time being.

**Comment by dluc** [comment]
In the PR it defaults to `true` for redirections though
```
private const bool AUTO_REDIRECT_DEFAULT = true;
```
the default should be `false` so one can opt-in intentionally.

There are many worrying points about this proposal, and even assuming a developer is making the choice intentionally, it would make it easier introducing bugs in a service-to-service interaction.

For instance, browsers are continuously updated to protect users from cross-domain data leaks. Automatically following the redirection would need similar protections. For instance cookies and auth headers could be sent to the wrong destination. 

There are many redirection types (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Redirections), should they be managed differently?

Should the application include integration tests to verify how and if redirections work for POST/PUT/DELETE, in combination with HTTPS and different browser types?

The code would need protection against infinite redirection loops.

Considering the complexity of the topic, we probably won't introduce this change.

**Comment by KeesCBakker** [comment]
Currently the redirect is done by the HTTP client by default - that's why I defaulted it to true - to be backwards compatible.
